name: first_workflow
on: push
jobs:
  lint_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: All steps together
        uses: actions/checkout@v3
        run: |
              npm ci
              npm run lint
              npm test
              npm run build