name: lint_test_deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - name: lint execution
        run: |
              npm ci
              npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: test execution
        run:  npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: deployment execution
        run: npm run build
